---
# file: roles/docker-svn/tasks/main.yaml

- name: docker_container.conf dir
  file:
    state: directory
    path: '{{ docker_restore_config_base_dir }}/{{ svn_dv_name }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
    recurse: no

# *****************************************************************************
# backup script part

- name: Assemble dir for backup scripts
  file:
    path: /usr/libexec/bacula/backup-scripts
    state: directory

- name: Create before_backup script
  template:
    src: before_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.before_backup.svn

- name: Create after_backup script
  template:
    src: after_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.after_backup.svn

# *****************************************************************************
# update the Docker restore config

- name: exists - state file
  stat:
    path: '{{ docker_restore_config_base_dir }}/{{ svn_dv_name }}/restore.date.txt'
    get_checksum: False
    get_md5: False
  register: st_svn_restore

# *****************************************************************************
# Update or make the image.
- name: Checkout image repo
  git:
    repo: '{{ svn_image_repo }}'
    version: master
    dest: '{{ docker_projects_dir }}/docker-svn'

- name: build image
  docker_build:
    image_name: '{{ svn_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    dockerfile_dir: '{{ docker_projects_dir }}/docker-svn'

# *****************************************************************************
# Create the data volumes

- name: data-volume container
  docker_datavolume:
    image_name: '{{ svn_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    data_volume_container_name: '{{ svn_dv_name }}'

# *****************************************************************************
# Start the data container running

- name: start container
  docker_container:
    detach: true
    env:
      SVN_HOSTNAME: '{{ container_addr_map.svn.hostname }}'
      SVN_LDAP_PASSWORD: '{{ openldap_proxyagent_password }}'
    hostname: '{{ container_addr_map.svn.hostname }}'
    image: '{{ svn_image_name }}:{{ docker_image_tag }}'
    link:
      - '{{ openldap_container_name }}:ldap'
    name: '{{ svn_container_name }}'
    ports: '{{ container_port_map.svn.port_args }}'
    restart_policy: '{{ docker_restart_policy }}'
    volumes_from:
      - '{{ openssl_dv_name }}'
      - '{{ svn_dv_name }}'

# *****************************************************************************
# restore?

- include_tasks: restore.yml
  when: st_svn_restore.stat.exists == False
