---
# file: roles/docker-svn/tasks/restore.yaml

# *****************************************************************************
# Setup the directory where the backup and restore is to take place

- name: restore dir
  file:
    state: directory
    path: '{{ svn_docker_restore_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no
    setype: svirt_sandbox_file_t

# *****************************************************************************
# Get data from tape

- name: find files
  files_in_dir:
    path: '{{ svn_docker_restore_dir }}'
  register: svn_repo_backup

- name: data from tape
  bacula:
    command: restore
    storage: '{{ bacula_storage }}'
    fileset: '{{ bacula_fileset }}'
    dest: '{{ bacula_dest }}'
    path_to_restore: '{{ svn_docker_backup_dir }}'
  when: svn_repo_backup.file_list == []

- name: find files
  files_in_dir:
    path: '{{ svn_docker_restore_dir }}'
  register: svn_repo_backup

- name: File permissions
  file:
    path: '{{ svn_docker_restore_dir }}/{{ item }}'
    state: touch
    owner: root
    group: root
    mode: 'u=rwx,g=rwx,o='
  with_items: '{{ svn_repo_backup.file_list | default([]) }}'

# *****************************************************************************
# restore the svn backup

- name: restore svn repositories
  docker_container:
    command: ['import', '{{ svn_repos }}']
    detach: False
    image: '{{ svn_image_name }}:{{ docker_image_tag }}'
    name: 'svn_restore'
    volumes_from:
      - '{{ svn_dv_name }}'
    volumes:
      - '{{ svn_docker_restore_dir }}:/tmp/import_export:z'
  when: not((svn_repos is undefined) or (svn_repos is none) or (svn_repos|trim == '')) or svn_repo_backup.file_list != []

- name: remove svn-restore container
  docker_container:
    name: 'svn_restore'
    state: absent

- name: start container
  docker_container:
    name: '{{ svn_container_name }}'
    restart: True
    state: started

# *****************************************************************************
# cleanup

- name: Remove files
  file:
    path: '{{ svn_docker_restore_dir }}'
    state: absent

- name: State file
  shell: 'date --rfc-3339=seconds > {{ docker_restore_config_base_dir }}/{{ svn_dv_name }}/restore.date.txt'
  when: st_svn_restore.stat.exists == False
